### ISSUE TITLE
Line symbol patterns?

### ISSUE THREAD

**Issue by davenquinn** [protomaps/protomaps-leaflet#102]
Hello, what an interesting library and broader project! The PMTiles format seems particularly innovative.

I'm working on geologic maps and one of our key needs is line patterns with symbols and dashing patterns, to represent different types of folds, faults, etc. (See an example here: https://macrostrat.org/map/#x=-114.633&y=51.0354&z=8.6&show=line-symbols,geology).

Is this functionality available in protomaps, or do you see a straightforward pathway to adding them? I might be willing to work on a pull request if it fit into the roadmap.

**Comment by bdon** [comment]
That functionality is not available directly in this library, but you could implement it via custom Symbolizer that calls the Canvas API. It looks like your Mapbox/MapLibre solution is looking quite well through, and for most sophisticated use cases like yours I would recommend that over this library.

**Comment by bdon** [comment]
I'm making this library more focused for 2.0, and the built in set of Symbolizers to support the default basemaps will be the only ones, though anything on Canvas is possible with custom Symbolizers. #112
