### ISSUE TITLE
Map style missing

### ISSUE THREAD

**Issue by allesan** [protomaps/protomaps-leaflet#103]
I've converted mbtiles to pmtiles and I've tried with https://protomaps.github.io/PMTiles, everything seams fine.
But when I load the pmtiles in website with protomaps.js and leafletjs I get only this.

![image](https://user-images.githubusercontent.com/8148733/220318393-4f5d652b-1036-4006-9d32-995d1905893d.png)

My code is simple:

`    const modalMap = L.map('modal-map')
    var layer = protomaps.leafletLayer({
        url:'/mytiles.pmtiles',
    })
    layer.addTo(modalMap)
`

**Comment by bdon** [comment]
Please see https://github.com/protomaps/protomaps-themes/issues/15 to see if it's the same issue and describe how you created your MBTiles.

**Comment by allesan** [comment]
Well, it looks the same as that issue, but I am using leafletjs and I'm not sure how to apply protomaps themes?

As for creation of MBTiles, I've download pbf files from Geofabrik, and converted them with https://github.com/systemed/tilemaker
And than to pmtiles with https://github.com/protomaps/go-pmtiles

**Comment by allesan** [comment]
Also, when I use small portion of the map that I downloaded through https://app.protomaps.com/downloads/small_map it works fine with the same code.

**Comment by bdon** [comment]
Hi, please see answer here: https://github.com/protomaps/protomaps-themes/issues/16#issuecomment-1442908200

**Comment by allesan** [comment]
I've read that but I'm still not sure is there a way to fix this or not when creating maps/pmtiles like this .pbf > tilemaker > go-pmtiles/pmtiles

**Comment by bdon** [comment]
@allesan yes, that won't be possible without either writing either a custom Tilemaker LUA or protomaps.js style in JavaScript.

**Comment by sing78** [comment]
I have the same issue,I used Planetiler-Openmaptiles to download a .mbtiles file and then converted to .pmtiles.
Then,I added an Openmaptiles style using this code:

var layer = protomaps.leafletLayer({
        url: 'italy.pmtiles',
        style: 'https://openmaptiles.github.io/osm-bright-gl-style/style-cdn.json'
        
      });

Still I cannot view the map correctly.Any hints?

**Comment by bdon** [comment]
Hi, protomaps.js is not compatible with JSON styles, those are designed for MapLibre GL and Mapbox GL. (There is some existing code for this in the source code but it is not complete enough for general use and will be deprecated)

**Comment by sing78** [comment]
Hi, thanks,that makes sense.
Where can I find info, how to add a "style" when using protomaps.js with Leaflet?
Are there any styles related to protomaps (apart from Opentilemaps styles) or is this something being worked on?

**Comment by bdon** [comment]
Hi, the best example of a style is the default style in the repo here: https://github.com/protomaps/protomaps.js/blob/main/src/default_style/style.ts

There isn't any other public and open source styles AFAIK, the main use case is styling your own vector data from tippecanoe which is specific to your dataset. Going forward most style development is going to be focused on the MapLibre GL renderer instead.

**Comment by sing78** [comment]
@bdon Thank you, that makes sense.

**Comment by bdon** [comment]
@tobilg If you want to use this leaflet library with the OMT+Tilemaker created data schema, you need to write your own style. Otherwise you can use https://github.com/protomaps/basemaps/ which creates the data schema assumed by this library.

**Comment by bdon** [comment]
Default style has been updated to tileset v3.
