### ISSUE TITLE
Clarification on versioning and API stability needed

### ISSUE THREAD

**Issue by wolfskaempf** [protomaps/protomaps-leaflet#108]
First of all, thank you @bdon and everyone on the protomaps.js team for your work, this project is looking seriously promising!

It would be really helpful if some clarification about your plans on versioning and API stability was added to the project status section of the README.

https://github.com/protomaps/protomaps.js/blob/517651a2f69f3f500d7af0a63a6c34b772cba252/README.md?plain=1#L50-L52

The current version of from October 2021 and I suspect since then there could have been some changes about how versioning and breaking changes are handled that could be mentioned in that section.

Thank you for considering this!

**Comment by bdon** [comment]
@wolfskaempf to be frank, at this point the project has found a specific niche - lightweight vector mapping and labeling for applications that already use Leaflet. Applications that are more map-centric and need more advanced features are better served by MapLibre GL JS, and there's now pretty good PMTiles support for that via `addProtocol`. So development has slowed as I've focused more effort on PMTiles + MapLibreGL as well as an upcoming open source tileset. 

With that said, what I'm thinking about doing is making a 2.0 release that removes some superfluous features (the incomplete JSON styling API), and cleans up the developer-facing API.

**Comment by wolfskaempf** [comment]
@bdon Thank you for the fast clarification, that's really helpful information! 

To be frank, I'm here because PMTiles are really appealing and because in older projects I've come into contact with Leaflet and I was just looking for a way to self-host a basemap. By using PMTiles, the project is not at the mercy of for example Mapbox who could end their free tier any day and hosting PMTiles doesn't require an entire DevOps team managing a tiles server, which is awesome.

That leads me to a follow up question, if I may: If I were to start a web application centered around a map component with a few pins from scratch today, would you then rather recommend the PMTiles + MapLibreGL stack instead of PMTiles + protomaps.js + Leaflet as the more future-proof option?

If that question goes too far out of topic from this issue I totally understand, yet I think people who are looking at PMTiles and protomaps.js today could really benefit from your thoughts or recommendations as a domain expert in web based maps.

**Comment by bdon** [comment]
Yes, I would recommend Maplibre GL + PMTiles for greenfield projects now. 

The major drawbacks I see to maplibre GL are:
* lack of high quality plugins compared to Leaflet
* Huge bundle size, especially if you include the RTL text plugin - this matters less now than a few years ago as websites have gotten bigger
* You need to host fonts too along with your pmtiles archive. I have been working on making this easier with https://github.com/maplibre/font-maker

Are any of those concerns vital for your project?

**Comment by wolfskaempf** [comment]
@bdon Thank you a lot for being so forthcoming with your help! 

The main goal of the project is to allow residents of my hometown to easily find e.g. a school or kindergarten that matches their search criteria (like school-type (Germany has a lot of different ones), age-range, extracurricular activities) and then see which of the matching ones are nearby because the search results are displayed on a map. When clicking on one of the pins on the map, it should be possible to show a pop-up with further information about the school / kindergarten or other educational facility.

Since it'll be a complete greenfield project based on Angular, I think I'll just do a prototype following your advised stack with MapLibre GL JS + PMTiles and see how it works out :)

Thank you a lot for sharing your domain expertise with the community!

**Comment by bdon** [comment]
See https://github.com/protomaps/protomaps-leaflet/issues/112 for the transition steps from `protomaps` to `protomaps-leaflet`

**Comment by bdon** [comment]
Closing this issue as it seems to be revolved, and more progress will be made in major version 2.0 that removes many features like JSON styles and interactive features, since applications needing those should use MapLibre instead. 

https://github.com/protomaps/protomaps-leaflet/pull/129
