### ISSUE TITLE
Unpkg URL in "How to use" section appears broken

### ISSUE THREAD

**Issue by hampelm** [protomaps/protomaps-leaflet#113]
The script url in the Readme appears to have a broken redirect:  https://unpkg.com/protomaps@latest/dist/protomaps-leaflet.min.js to https://unpkg.com/protomaps@1.23.1/dist/protomaps-leaflet.min.js

Changing the URL to the latest release in the repo, 1.24.0, also does not work: https://unpkg.com/protomaps@1.24.0/dist/protomaps-leaflet.min.js

**Comment by bdon** [comment]
fixed, thanks
