### ISSUE TITLE
how to send header to protomapsL.leafletLayer()

### ISSUE THREAD

**Issue by geekypradip** [protomaps/protomaps-leaflet#114]
if my `.pmtiles` file need a header(bearer token ) for access, how to send the header with URL

**Comment by bdon** [comment]
What kind of header is it? You can implement a custom PMTiles `source`, or https://github.com/protomaps/PMTiles/pull/112 will make this easier in a few weeks

**Comment by geekypradip** [comment]
My question is when I am sending  the URl like 
`const url="https://somename.pmtiles"    //this file can be access by bearer token `
`var layer = protomapsL.leafletLayer({
        url:url ,
        paint_rules: PAINT_RULES,
      });`

is there any option where I can send the token    with the URL

**Comment by bdon** [comment]
Is the bearer token constant for the entire lifetime of your webpage or do you have to update it?

**Comment by geekypradip** [comment]
I need to update it

**Comment by bdon** [comment]
Then the solution we'll have in https://github.com/protomaps/PMTiles/pull/112 will not work, you will need to create your own implementation `Source` similar to `FetchSource` that lives in your code and holds the state of your token, then create a `PMTiles` instance and pass that into `leafletLayer`

https://github.com/protomaps/PMTiles/blob/main/js/index.ts#L283

**Comment by bdon** [comment]
If your token does not change, then you can create a `FetchSource` and pass in a Headers object; I am planning to implement this in about 2 weeks.

**Comment by bdon** [comment]
example here: https://github.com/protomaps/protomaps-leaflet/blob/main/examples/pmtiles_headers.html
