### ISSUE TITLE
How to insert headers into tilecache fetch request

### ISSUE THREAD

**Issue by drzhouq** [protomaps/protomaps-leaflet#116]
@bdon I like the idea of pmtiles a lot. However, it seems that there is no easy way to incorporate some security check (via request header token) https://github.com/protomaps/protomaps-leaflet/blob/754458357228c5a82e85930812cd461d0e9f7d59/src/tilecache.ts#L195

How would you incorporate the fetch request to pass on additional headers?

Thanks, Brandon, for your fantastic job on PMTiles.

**Comment by bdon** [comment]
if you are using pmtiles you can pass a custom FetchSource with your own headers:

https://github.com/protomaps/PMTiles/blob/main/js/index.ts#L287
