### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by DenisBotev** [protomaps/protomaps-leaflet#120]
First of all, a big thanks for creating and supporting the project! I'm a total newbie to maps and I apologize in advance if I'm raising an issue that is easily fixable, or if I'm writing this on the wrong repo. 
I've successfully deployed my own map of the entire world on Cloudflare by following [this guide](https://docs.protomaps.com/deploy/cloudflare) and everything seems to be working OK.

However, I realized  that I have some data missing from my map when compared to the demo. For example, this is an area of central Tokyo as seen on the [ Simple Leaflet demo](https://protomaps.github.io/protomaps-leaflet/examples/leaflet.html#17/35.68629/139.75633) :
![tokyo leaflet demo](https://github.com/protomaps/protomaps-leaflet/assets/48261726/1d0f45fc-de80-44e8-b07b-4e018af0de26)

and here is how it looks like on my version of the map:
![tokyo own copy](https://github.com/protomaps/protomaps-leaflet/assets/48261726/46ba12e0-42c3-4af9-aa5a-3a65c21934b9)

As another larger example, here is a screenshot of zoom level 4, and it can be seen that a large part of Japan is missing:
![japan zoom 4 own copy](https://github.com/protomaps/protomaps-leaflet/assets/48261726/e20bc1ef-723a-4c39-97e5-9d4fc03bf33a)

I ran `pmtiles verify` on my local copy of the .pmtiles file and no issues were raised.

Also, sometimes labels are blurry, but I think I should raise a separate issue for this.

Thanks again

**Comment by DenisBotev** [comment]
As a followup - I tested my tiles by loading my .pmtiles URL in both the PMTiles Viewer and on [](https://maps.protomaps.com/) and both displayed everything correctly, so it isn't a data integrity issue.
Any suggestions are greatly appreciated.

**Comment by bdon** [comment]
The style in this repo for this rendering library still depends on the Basemap V2 here: https://docs.protomaps.com/basemaps/downloads I haven't had the time to update it to V3 yet.

**Comment by DenisBotev** [comment]
Hi Brandon, thank you for the quick reply and a Happy New Year!

If I'm understanding things correctly, I need to download the last V2 version of the basemap [here ](https://r2-public.protomaps.com/protomaps-sample-datasets/protomaps-basemap-opensource-20230408.pmtiles) and replace it in my R2. Is this correct? 

Also, since the V2 comes with some disadvantages compared to the V3 as seen in the [blog](https://protomaps.com/blog/pmtiles-v3-whats-new), do you have any suggestions on an alternative way to use the V3? 
 
Thanks again

**Comment by bdon** [comment]
@DenisBotev the PMTiles specification and the basemap project are different software projects with their own versions. The V2 basemaps you linked use PMTiles version 3, so it has all the new advantages. I'm afraid I can't prioritize dev work or reviewing PRs in this repo in the short term, but you may be able to design your own V3 set of paintRules/labelRules.

**Comment by DenisBotev** [comment]
I think I understand, and I've managed to get the map running properly using the older basemap that I linked. 

If you'd like I can provide some extra comments in the documentation for future users who might run into the same problem.

Thanks again for your help!

**Comment by bdon** [comment]
Started to add some notes in the docs regarding protomaps-leaflet and basemaps v2 https://github.com/protomaps/docs/pull/19
