### ISSUE TITLE
Not able to view PMTILE inside map

### ISSUE THREAD

**Issue by Na-eng-web** [protomaps/protomaps-leaflet#135]
![Screenshot 2024-02-08 at 6 56 33 PM](https://github.com/protomaps/protomaps-leaflet/assets/73187934/65e497c1-b962-4309-ad40-b7fa8771d226)

i am using this code 
/////////////////////////////////////////

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Protomaps with Leaflet</title>
    
    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
    />
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"></script>
    <script src="https://unpkg.com/protomaps-leaflet@1.24.0/dist/protomaps-leaflet.min.js"></script>
    <style>
      /* Define a CSS style for the map container */
      #map {
        height: 1000px;
      }
    </style>
  </head>
  <body>
    
    <div id="map"></div>

    <script>
      // Initialize a Leaflet map
      const map = L.map("map").setView([0, 0], 2);
      // Add a base map layer (e.g., OpenStreetMap)
      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      }).addTo(map);

      let LABEL_RULES = []; // ignore for now

      // Add a Protomaps layer to the map
      var layer = protomapsL.leafletLayer({
        url: "/large_contour_367_1_8 (1).pmtiles",
      });
      layer.addTo(map);
    </script>
  </body>
</html>
 
/////////////////////////////////////////

its works fine in 

[https://protomaps.github.io/PMTiles/#map=0.81/0/0](https://protomaps.github.io/PMTiles/#map=0.81/0/0)

**Comment by bdon** [comment]
We can't reproduce your issue without access to the `large_contour_367_1_8 (1).pmtiles` file.

**Comment by Na-eng-web** [comment]
[link to download pmtile](https://ytdevc.deepmatrix.io/content/public/pmtiles/large_contour_367_1_8.pmtiles)

**Comment by Na-eng-web** [comment]
[link to download pmtile](https://drive.google.com/file/d/11VMjSX5yXzqOgp7_yukd18pyeeo64Jkr/view?usp=sharing)

**Comment by bdon** [comment]
You need to write layer styling to address the layer `zcta` which you specified. From what I Can tell the file is working as intended.
