### ISSUE TITLE
Feature request: example of selecting layers in Protomaps Leaflet maps

### ISSUE THREAD

**Issue by jaanli** [protomaps/protomaps-leaflet#136]
Use case: Protomaps is amazing, and I would love to see an example of enabling a user to select layers to hide or show in a Protomaps + leaflet map. Here is an example of one type of UI/UX supported by Leaflet - https://opengeo.tech/maps/leaflet-panel-layers/

If there is no example I’d be happy to try to make one!!

**Comment by bdon** [comment]
Nice demo! that's a general Leaflet example though, not one specific to protomaps-leaflet, which just adds a normal layer, so I don't think it's relevant.

**Comment by jaanli** [comment]
Got it, thank you Brandon - will try to get it working alongside a protomaps-leaflet later then. Happy to contribute it if it could help others reuse!
