### ISSUE TITLE
Missing Greenland

### ISSUE THREAD

**Issue by chriscdn** [protomaps/protomaps-leaflet#149]
First, protomaps is amazing.  Thank you to all the contributors.

I'm not sure where this is happening, but here's my setup:

- copied `20240410.pmtiles` from https://maps.protomaps.com/builds/ to an S3 bucket
- setup `pmtiles` in serve mode on my webserver
- installed `protomaps` and `leaflet` from npm in my client application
- configured leaflet to use protomaps:

```js
protomaps
      .leafletLayer({
        url: "https://protomaps.mydomain.com/20240410/{z}/{x}/{y}.mvt",
      })
      .addTo(map);
```

This works.  However, there's an issue with land masses disappearing at certain zoom levels.  Attached are two screenshots showing a zoom level with Greenland missing, and another zoom level where all land is missing.

![no_greenland](https://github.com/protomaps/protomaps-leaflet/assets/363330/1dc06613-d796-4031-98a4-a87a6d60f7d9)
![no_land](https://github.com/protomaps/protomaps-leaflet/assets/363330/df19fb59-9969-43f3-ba84-2c5f2de3fa6c)

Is this a known issue, or is there something I didn't consider in my setup?  Thanks.

**Comment by bdon** [comment]
You should not use the npm package `protomaps`, that is deprecated; you need `protomaps-leaflet`. Can you try to reproduce on the latest version of that?

**Comment by chriscdn** [comment]
That did it, thank you.

I look forward to diving into this a little more, and seeing what options are available.  It's an incredible thing you've built here...

**Comment by bdon** [comment]
I updated https://www.npmjs.com/package/protomaps with a new version as an empty repo with a README link to the new package (protomaps-leaflet)

**Comment by chriscdn** [comment]
If it helps, npm lets you deprecate packages, which places a large deprecation warning on the page. Simply open the page on npm, click on the settings tab, and look for the deprecate package button.

**Comment by bdon** [comment]
Thanks, I might re-use this package name in the future, likely to rename `protomaps-themes-base` to `protomaps`.  Not sure how deprecating and un-deprecating would affect other tools in the NPM ecosystem so playing it safe for now.
