### ISSUE TITLE
protomaps-leaflet/examples/

### ISSUE THREAD

**Issue by vitoborneo** [protomaps/protomaps-leaflet#150]
Some examples return blank pages. I tried
leaflet.html
multi_source.html
sandwich.html
sprites.html

**Comment by bdon** [comment]
These return blank for you?

https://protomaps.github.io/protomaps-leaflet/examples/leaflet.html
https://protomaps.github.io/protomaps-leaflet/examples/multi_source.html
https://protomaps.github.io/protomaps-leaflet/examples/sandwich.html
https://protomaps.github.io/protomaps-leaflet/examples/sprites.html

Are you replacing the API key with one designated for your domain?

**Comment by vitoborneo** [comment]
Ok, now it works.
I found example pages of locally loaded vector PMTiles files working with protomaps.min.js version 2.0.1.
Now with protomaps-leaflet.min.js these pages doesn't works.
Where can I find a demo of a vector file PMTiles and protomaps-leaflet.min.js?
Thank you

**Comment by bdon** [comment]
Can you provide an example of the non-working code?

**Comment by vitoborneo** [comment]
https://bertt.wordpress.com/2023/01/06/creating-vector-pmtiles-with-tippecanoe/
live demo see
https://bertt.github.io/opendata/world/railroads
Thanks

**Comment by bdon** [comment]
Opened PR: https://github.com/bertt/opendata/pull/1
