### ISSUE TITLE
Can't resolve internal file imports in distribution package

### ISSUE THREAD

**Issue by claustres** [protomaps/protomaps-leaflet#158]
Switching from v1 to v3 in an app using WebPack but without using TS I struggled with import errors like this:
![image](https://github.com/protomaps/protomaps-leaflet/assets/2647117/1066d7c6-3e1f-4556-8e1f-b93802db669c)

It appears that the missing `.js` extension of the import statements in the `dist` folder get WebPack messy. Just to confirm the issue I used https://github.com/beenotung/fix-esm-import-path to fix it like this `fix-esm-import-path node_modules/protomaps-leaflet/dist/index.js`. However, I am not a TS gourou so I guess there is a compile option to do so as it would ease integration.

**Comment by claustres** [comment]
I made some research and it seems that the best thing to do is to specify file extension at the source level (ie TypeScript) otherwise you have to use the kind of hacking tool I used like babel plugins or so.

**Comment by bdon** [comment]
Can you create and share a minimal WebPack example that reproduces your problem without TypeScript?

**Comment by claustres** [comment]
Probably not so easy but I can first share the [setup](https://github.com/kalisio/kano/blob/master/quasar.config.js) of our application, which is based on [Quasar](https://quasar.dev/quasar-cli-webpack/quasar-config-file) [Webpack support](https://quasar.dev/quasar-cli-webpack/handling-webpack).

**Comment by bdon** [comment]
We're likely going to migrate the build scripts to https://github.com/egoist/tsup which should improve the CommonJS situation, and also stop using default exports.

**Comment by bdon** [comment]
Can you please try [4.0.0-alpha.0](https://www.npmjs.com/package/protomaps-leaflet/v/4.0.0-alpha.0)

**Comment by claustres** [comment]
It seems to work fine now @bdon, thanks.

**Comment by bdon** [comment]
This major release will also move from bundled ESM modules/CJS to unbundled, which is what people expect for ES6 frontend and NodeJS projects. Waiting on https://github.com/protomaps/protomaps-leaflet/issues/162#issuecomment-2250641439 to see that there is a workable resolution for ESM-in-the-browser.

**Comment by bdon** [comment]
v4.0.0 released: https://www.npmjs.com/search?q=protomaps-leaflet
