### ISSUE TITLE
Rendering artefact with symbolizers created from Mapbox style

### ISSUE THREAD

**Issue by claustres** [protomaps/protomaps-leaflet#159]
In an [effort](https://github.com/kalisio/leaflet-pmtiles/issues/1) to pursue the support of this kind of style, we get pretty good results but we struggle with a rendering artefact that maybe someone could help identify the root cause. It appears that some lines seems to be "filled", it's certainly not a bug but probably a misusage, here is a rendering at different zoom levels:
![Capture d’écran du 2024-07-12 11-57-17](https://github.com/user-attachments/assets/de323ad3-b6ba-44da-be2c-6b9be3ce5943)
![Capture d’écran du 2024-07-12 11-57-21](https://github.com/user-attachments/assets/4fd407fa-5b0b-4937-920c-202c7d74b6a5)
![Capture d’écran du 2024-07-12 11-57-25](https://github.com/user-attachments/assets/a6bcfa27-2c3e-4996-93d5-842a19fbbf20)

Any insight is welcome, thanks.

**Comment by bdon** [comment]
Are you attempting to use a PolygonSymbolizer on a line feature?

You should first filter any rules that use polygon fill operations to only features with polygon geometries.

Are you mutating the context2d of the canvas in a custom Symbolizer and not resetting it at the end?

**Comment by claustres** [comment]
Find it out with your help and actually the help of [feature picking](https://github.com/protomaps/protomaps-leaflet/issues/160) to identify the failing features/rules !

I was not correctly manage filtering on geometry types so that some polygon symbolizers was run over line features.

Thanks.
