### ISSUE TITLE
ESM build target

### ISSUE THREAD

**Issue by prushforth** [protomaps/protomaps-leaflet#162]
I noticed that the [dist/index.js](https://unpkg.com/protomaps-leaflet@3.1.2/dist/index.js) is not actually the output of the build-module script (is it supposed to be?).  Perhaps if the output of that script was available on CDN it would allow use via `<script type=module src="https://unpkg.com/protomaps-leaflet@latest/dist/index.js"></script>`

THANK YOU for an amazing project!

**Comment by bdon** [comment]
You're right, the `build-tsc` task is clobbering the other files. I will need to push a new major release that will change the module paths, probably adding a `esm/` folder to the distribution. PR coming.

**Comment by bdon** [comment]
Can you please try [4.0.0-alpha.0](https://www.npmjs.com/package/protomaps-leaflet/v/4.0.0-alpha.0)

**Comment by prushforth** [comment]
> Can you please try [4.0.0-alpha.0](https://www.npmjs.com/package/protomaps-leaflet/v/4.0.0-alpha.0)

I'm using grunt-rollup. I reference the esm in my index.js for input to rollup like so:

```javascript
import { leafletLayer } from '../../node_modules/protomaps-leaflet/dist/esm/index.js';
import {  LineSymbolizer,  PolygonSymbolizer} from '../../node_modules/protomaps-leaflet/dist/esm/index.js';
```

When I run the rollup, I get a few issues:

```logfile
Running "rollup:main" (rollup) task
'@mapbox/point-geometry' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
'color2k' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
'@mapbox/vector-tile' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
'pbf' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
'pmtiles' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
'rbush' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
'potpack' is imported by node_modules/protomaps-leaflet/dist/esm/index.js, but could not be resolved – treating it as an external dependency
No name was provided for external module '@mapbox/point-geometry' in output.globals – guessing 'X'
No name was provided for external module 'color2k' in output.globals – guessing 'color2k'
No name was provided for external module '@mapbox/vector-tile' in output.globals – guessing 'vectorTile'
No name was provided for external module 'pbf' in output.globals – guessing '_t'
No name was provided for external module 'pmtiles' in output.globals – guessing 'pmtiles'
No name was provided for external module 'rbush' in output.globals – guessing 'Et'
No name was provided for external module 'potpack' in output.globals – guessing 'qt'
```

When I load the test page I see a console error log:

```console
Uncaught ReferenceError: X is not defined
    at mapml.js:10943:3
```

The technique I was using up to now was to run your `npm run build-module` and to import those symbols from the index.js created.

**Comment by bdon** [comment]
Can you upload your full project so others can reproduce?

**Comment by prushforth** [comment]
The branch I have been experimenting with is on 3.1.2, I changed that to depend on [4.0.0-alpha0](https://www.npmjs.com/package/protomaps-leaflet/v/4.0.0-alpha.0) in [this branch](https://github.com/prushforth/Web-Map-Custom-Element/tree/pmtiles-leaflet-4.0.0-test).  In there, the file src/mapml/index.js imports directly from the node_modules-installed esm/index.js.  Maybe I'm doing that step wrong.  Probably!

**Comment by prushforth** [comment]
I tried changing the import to `import * as protomapsL from "..\..\node_modules\protomaps-leaflet\dist\esm\index.js"` and then defining my own references to protomapsL.leafletLayer etc., but the result is the same. 

I think that while the protomaps-leaflet dependencies are installed in my node_modules, for some reason the importing being done by  "..\..\node_modules\protomaps-leaflet\dist\esm\index.js" is not finding the various packages i.e. this message

```logfile
'@mapbox/point-geometry' is imported by node_modules\protomaps-leaflet\dist\esm\index.js, but could not be resolved – treating it as an external dependency
```
 is a clue.  Maybe it's the grunt-rollup plugin I'm using. I'll try updating that.

**Comment by prushforth** [comment]
I added the \@rollup/plugin-node-resolve plugin to my grunt-rollup plugin, and most of the module resolving errors went away, but it still doesn't complete the build, finishing with this message:

```logfile
Running "rollup:main" (rollup) task
Warning: 'default' is not exported by node_modules/@mapbox/point-geometry/index.js, imported by node_modules/protomaps-leaflet/dist/esm/index.js Use --force to continue.

Aborted due to warnings.
Done.
```

**Comment by bdon** [comment]
Are the initial ESM issues unique to this package, or are you successfully using other ESM packages that aren't bundled?

I will take a look at the `point-geometry` issue, thanks.

**Comment by prushforth** [comment]
> Are the initial ESM issues unique to this package, or are you successfully using other ESM packages that aren't bundled?

I don't believe any of the dependencies we currently have  have any dependencies of their own, so bundling has not come up yet.  We have forked code (and licenses) from some projects directly into our project, so deps of deps hasn't been an issue so far.  I noticed that the build-module task at protomaps-leaflet 3.1.2 produces an index file that doesn't have this problem, and maybe the --bundle option is not being passed to tsup.

**Comment by bdon** [comment]
Can you please try again with [4.0.0-alpha.1](https://www.npmjs.com/package/protomaps-leaflet/v/4.0.0-alpha.1)

**Comment by bdon** [comment]
> maybe the --bundle option is not being passed to tsup.

Other users of the library prefer that the library does not bundle its dependencies, except in the script-includes case which need to bundle to work. So this 4.0.0 will change the ESM and CJS output to unbundled.

**Comment by bdon** [comment]
v4.0.0 has been published https://www.npmjs.com/search?q=protomaps-leaflet

please reopen if you encounter any new build issues.
