### ISSUE TITLE
Minified version does not export a global object since v4

### ISSUE THREAD

**Issue by claustres** [protomaps/protomaps-leaflet#170]
With `<script src="https://unpkg.com/protomaps-leaflet@latest/dist/protomaps-leaflet.min.js"></script>` the following error is raised in the HTML page since latest version: `ReferenceError: protomapsL is not defined`.

Using `<script src="https://unpkg.com/protomaps-leaflet@latest/dist/protomaps-leaflet.js"></script>` it works as usual.

**Comment by bdon** [comment]
The `photomaps-leaflet.js` build output is already minified, so there is no `.min.js` version.

**Comment by claustres** [comment]
Thank you for feedback, I was probably looking as some old examples and now realized that they were changed a couple of months ago in https://github.com/protomaps/protomaps-leaflet/commit/aa6a75f9a3e39504b6595b0c56140fd9b32523d0.
