### ISSUE TITLE
L is not defined

### ISSUE THREAD

**Issue by prushforth** [protomaps/protomaps-leaflet#175]
I am trying to convert my project to es modules.  I import protomaps-leaflet like so: `import * as protomapsL from 'protomaps-leaflet';`.  

I'm getting a runtime error because the global L variable is no longer defined (seeing as I'm importing Leaflet, too).  

```log
ReferenceError: L is not defined
    at leafletLayer (mapmlviewer.js:37561:49946)
```

the code is bundled, but I believe it stems from [this line](https://github.com/protomaps/protomaps-leaflet/blob/da47e14fe6ba0c4a17c3a8d3dc9921f0f99f39f0/src/frontends/leaflet.ts#L65). 

Is there anything I can do about this, or do you have an idea of how it can be managed on this end.  

Thanks!

**Comment by prushforth** [comment]
I figured out  a workaround, by creating window.L at runtime afer importing 'leaflet' it seems to work with that.

**Comment by bdon** [comment]
Thanks for the report, I'm not familiar with how to reconcile the Leaflet plugin model with modules, because all the plugins AFAIK assume `L` is in the global scope and do not bundle an implementation of Leaflet as a dependency. 

Do you have any examples of Leaflet plugins that work with both global `L` and modules that we could use as a template? It would require a major version bump of this library which is fine.

**Comment by prushforth** [comment]
> Do you have any examples of Leaflet plugins that work with both global L and modules that we could use as a template? It would require a major version bump of this library which is fine.

That's a good point I hadn't considered actually.  I did do a refactoring of a Leaflet plugin recently into esm syntax, and while don't know if the maintainer will accept it, because it's a change to the build system, the pr is [here](https://github.com/domoritz/leaflet-locatecontrol/pull/357).  I just bought the book on typescript, so I don't think I'll be much help, but willing to help test it if it comes out.  I guess Leaflet isn't quite ready to go fully public with their module code either and I imagine that the plugin ecosystem is a major consideration.
