### ISSUE TITLE
How to map a custom mapbox styles basemap to protomaps-leaflet - guidance

### ISSUE THREAD

**Issue by prushforth** [protomaps/protomaps-leaflet#178]
Hi,   I want to implement [this layer](https://www.arcgis.com/apps/mapviewer/index.html?layers=800d755712e8415aab301b9d55bc2800) in protomaps-leaflet, and have been having some success with the paint and text symbolizers, but I've run into challenges combining CenteredTextSymbolizers and IconSybmolizers in the same LABEL_RULES, and I was wondering if you could offer any basic guidance: what should I try and what can't be done yet? Thanks in advance for any info you can provide. As soon as I add the icon symbolizers, the text symbolizers don't render, and yes indeed it may be me.

**Comment by bdon** [comment]
If you want two symbolizers to appear together, you need to use a GroupSymbolizer to compose them, otherwise one will collide out the other.

**Comment by bdon** [comment]
example of circle and text https://github.com/protomaps/protomaps-leaflet/blob/main/src/default_style/style.ts#L611

**Comment by prushforth** [comment]
thanks that's helpful

**Comment by prushforth** [comment]
Should the GroupSymbolizer work with the ShieldSymbolizer in a similar way to the example? Thanks.

**Comment by bdon** [comment]
It ought to but not 100% sure. For sophisticated symbology maplibre has turned out to be a better fit, which is why the feature richness of this library remains limited.
