### ISSUE TITLE
Document layer names on the Rendering Tutorial page

### ISSUE THREAD

**Issue by pcmill** [protomaps/protomaps-leaflet#97]
I followed the [tutorial](https://protomaps.com/docs/protomaps-js/tutorial) to create the map style I wanted to achieve and found myself not knowing how the different layers are called. I eventually found this code: [default_style](https://github.com/protomaps/protomaps.js/blob/e2e0f379f33111391feb52a0dd6ca689dd2b402e/src/default_style/style.ts) which solved my personal problem.

Might be nice to create a list on the tutorial page (or elsewhere) so people can quickly start styling their own maps. Also documenting which Symbolizer you need for each layer could be useful. So `boundaries` is used with LineSymbolizer and `earth` is used with PolygonSymbolizer etc.

Last thing that would be really useful is a list of the different props that can be useful to filter. For example I used `pmap:min_admin_level === 2` to only show country boundaries.

**Comment by pcmill** [comment]
Just found [https://protomaps.com/docs/map-layers-tags](https://protomaps.com/docs/map-layers-tags). Then linking this page on the tutorial page might be enough :)

**Comment by bdon** [comment]
I've re-organized the Docs site completely:

https://protomaps.com/docs/frontends/basemap-layers contains the basemap layers

https://protomaps.com/docs/frontends/leaflet#custom-vector-data contains the old "tutorial" for writing Symbolizers. 

Will add some more links to/from GitHub and info on the possible props values. Thanks for the feedback!
